apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: le-clusterissuer
spec:
  rules:
  - host: grafana.iamalexsjones.com
    http:
      paths:
      - backend:
          serviceName: prometheus-grafana
          servicePort: 3000
  tls:
    - hosts:
      - grafana.iamalexsjones.com
      secretName: grafana-cert-manager-tls
