apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elastic-cb-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: le-clusterissuer
spec:
  rules:
  - host: elastic.crystalbasilica.co.uk
    http:
      paths:
      - backend:
          serviceName: elasticsearch-master-headless
          servicePort: 9200
  tls:
    - hosts:
      - elastic.crystalbasilica.co.uk
      secretName: elastic-cert-manager-ctls
