apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: nginx-ingress
    helm:
      parameters:
      - name:  service.type
        value: LoadBalancer
      valueFiles:
      - values.yaml
    repoURL: https://kubernetes-charts.storage.googleapis.com/
