apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elasticsearch
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: kibana
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://helm.elastic.co
    targetRevision: 7.6.1
